<?php

/**
 * @file
 * Provides functionality for handling trimmed out addresses.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function yse_address_formatter_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'help.page.yse_address_formatter') {
    $text = file_get_contents(__DIR__ . '/README.md');
    if (!Drupal::moduleHandler()->moduleExists('markdown')) {
      return '<pre>' . $text . '</pre>';
    }
    else {
      /** @var \Drupal\markdown\PluginManager\ParserManagerInterface $parser_manager */
      $parser_manager = \Drupal::service('plugin.manager.markdown.parser');
      $parser = $parser_manager->getDefaultParser([
        'render_strategy' => ['type' => 'none'],
      ]);
      return $parser->parse($text);
    }
  }
  return NULL;
}


/**
 * Implements hook_theme().
 */
function yse_address_formatter_theme() {
  return [
    'address_trim_by_postcode' => [
      'variables' => [
        'trim' => NULL,
        'given_name' => '',
        'additional_name' => '',
        'family_name' => '',
        'organization' => '',
        'address_line1' => '',
        'address_line2' => '',
        'postal_code' => '',
        'sorting_code' => '',
        'dependent_locality' => [],
        'locality' => [],
        'administrative_area' => [],
        'country' => [],
        'address' => NULL,
        'view_mode' => '',
      ],
    ],
    'address_trim_by_homecountry' => [
      'variables' => [
        'trim' => NULL,
        'given_name' => '',
        'additional_name' => '',
        'family_name' => '',
        'organization' => '',
        'address_line1' => '',
        'address_line2' => '',
        'postal_code' => '',
        'sorting_code' => '',
        'dependent_locality' => [],
        'locality' => [],
        'administrative_area' => [],
        'country' => [],
        'address' => NULL,
        'view_mode' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function yse_address_formatter_theme_suggestions_address_trim_by_postcode(array $variables) {
  $suggestions = [];
  $original = $variables['theme_hook_original'] . '__';
  $field = $variables['address']->getFieldDefinition();
  $entity_type_id = $field->getTargetEntityTypeId();
  $bundle = $field->getTargetBundle();
  $sanitized_view_mode = strtr($variables['view_mode'], '.', '_');

  $suggestions[] = $original . $entity_type_id . '__' . $sanitized_view_mode;
  $suggestions[] = $original . $entity_type_id . '__' . $bundle;
  $suggestions[] = $original . $entity_type_id . '__' . $bundle . '__' . $sanitized_view_mode;
  $suggestions[] = $original . $field->getName();
  $suggestions[] = $original . $entity_type_id . '__' . $field->getName();
  $suggestions[] = $original . $entity_type_id . '__' . $field->getName() . '__' . $bundle;

  return $suggestions;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function yse_address_formatter_theme_suggestions_address_trim_by_homecountry(array $variables) {
  $suggestions = [];
  $original = $variables['theme_hook_original'] . '__';
  $field = $variables['address']->getFieldDefinition();
  $entity_type_id = $field->getTargetEntityTypeId();
  $bundle = $field->getTargetBundle();
  $sanitized_view_mode = strtr($variables['view_mode'], '.', '_');

  $suggestions[] = $original . $entity_type_id . '__' . $sanitized_view_mode;
  $suggestions[] = $original . $entity_type_id . '__' . $bundle;
  $suggestions[] = $original . $entity_type_id . '__' . $bundle . '__' . $sanitized_view_mode;
  $suggestions[] = $original . $field->getName();
  $suggestions[] = $original . $entity_type_id . '__' . $field->getName();
  $suggestions[] = $original . $entity_type_id . '__' . $field->getName() . '__' . $bundle;

  return $suggestions;
}